### ISSUE TITLE
Incluir acessibilidade nos HTMLs

### ISSUE THREAD

**Issue by DanielleGuimaraesOliveira** [twistpucrio/fluffy-luff#29]

**Comment by DanielleGuimaraesOliveira** [comment]
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fluffy Luff</title>
    <link rel="shortcut icon" href="../img/fluffy-luff.png" type="image/x-icon">
    <link rel="stylesheet" href="../style/pagamento-e-dados.css">
</head>
<body>
    <div id="conteudo">
        <header id="header">
            <img id="logo" src="../img/fluffy-luff.png" alt="logo fluffy luffy. animal fofinho">
            <nav id="menu">
            <a href="#" aria-label="Clique aqui para voltar para página anterior.">Voltar</a>
                <a href="#" aria-label="Clique aqui para obter o pop-up de categorias de produtos do nosso site.">Categoria</a>
                    <input type="text" name="texto" id="texto" placeholder="Pesquisar produto" aria-label="Clique aqui para escrever oque deseja pesquisar."></input>
                <a href="#" aria-label="Clique aqui para ir ao seus favoritos.">Favoritos</a>
                <a href="#" aria-label="Clique aqui para ir ao seu carrinho de compras.">Carrinho</a>
            </nav>
        </header>
        <section id ="main">
            <h1>
            </h1>
            <a href="principal.html" aria-label="Clique aqui para ir para a página do produto.">
                <div class="moldura-produto" aria-labelledby="capivara">
                    <img class="imagem-produto" src="../img/capivara.webp" alt="Uma pelúcia de capivara marrom com um sorriso bobo e olhinhos fechados no fundo branco."/>
                </div>
            </a>
        </section>
        <footer id="footer">
            <p>
            <section id="creditos">
            Desenvolvido por: Danielle Guimarães, Julia Simão, Mariana Ribeiro e Vitória Carteri.<br/>
            Projeto TWIST-2024
            </section>
            <section id="versao">
            ©Fluffy Luff<br/>
            Versão do site: 1.0
            </section>
            </p>
            <a id="github" href="https://github.com/twistpucrio/fluffy-luff" target="_blank">
                <img src="../img/github.png" alt="logo do github." width="30" height="30">
            </a>
        </footer>
    </div>
</body>
</html>

**Comment by ju-s11** [comment]
tarefa meio terminada, mas vi faltou hj

**Comment by ju-s11** [comment]
ai ta em pausa por causa disso
